version: 2
jobs:
  build:
    docker:
      - image: debian

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            apt update && apt install --yes $(cat .circleci/dependencies.list)

      - run:
          name: build packages
          command: |
            make --directory=./uva-seas-thesis
            make --directory=./uva-seas-thesis/example
