version: 2
jobs:
  build:
    docker:
      - image: sunslayer/latex-docker

    steps:
      - checkout

      - run:
          name: build packages
          command: |
            make --directory=./uva-seas-thesis
            make --directory=./uva-seas-thesis/example
