.PHONY: default
default: beamercolorthemewahoo.sty beamercolorthemewahoo.pdf

beamercolorthemewahoo.sty:
beamercolorthemewahoo.pdf: beamercolorthemewahoo.sty example.pdf

example.pdf: beamercolorthemewahoo.sty

include ../../../../Makefile.mk
